include:
  - project: 'tauOS/ci'
    file: '/.rpm-build-template.yml'
  - project: 'tauOS/ci'
    file: '/.rpm-sign-template.yml'

variables:
    PACKAGE_VERSION: "1.0.0"
    PACKAGE_NAME: "tau-wallpapers"
    PACKAGE_ARCH: "noarch"

stages:
  - build
  - sign

build-job:
  stage: build
  before_script:
    - sudo dnf install -y kde-filesystem
  extends: .build

sign-job:
  stage: sign
  extends: .sign