include:
  project: 'tauOS/ci'
  file: '/.rpm-build-template.yml'

stages:
  - setup
  - build

setup-job:
  stage: setup
  script:
    - sudo dnf install -y kde-filesystem

build-job:
  stage: build
  variables:
    PACKAGE_VERSION: "37.0.0"
    PACKAGE_NAME: "tau-wallpapers"
    PACKAGE_ARCH: "noarch"
  extends: .build