include:
  - project: 'tauOS/ci'
    file: '/.rpm-build-template.yml'
  - project: 'tauOS/ci'
    file: '/.packagecloud-template.yml'

stages:
  - build
  - upload

build-job:
  stage: build
  before_script:
    - sudo dnf install -y kde-filesystem
  variables:
    PACKAGE_VERSION: "1.0.0"
    PACKAGE_NAME: "tau-wallpapers"
    PACKAGE_ARCH: "noarch"
  extends: .build

upload-job:
  stage: upload
  variables:
    PACKAGE_VERSION: "fedora/35"
  extends: .upload